axios:
  timeout:      7000
port:           3000
auth:
  expireDays:   180 # 六个月不使用则用户身份过期
  cipher:       aes-256-cfb
term:
  # 每年的三个学期名和开学日期
  # 开学日期必须是周一
  # 必须在每年暑假期间进行更新，不得早于春学期第18周结束，不得晚于短学期开学。
  17-18-1:      2017-8-28
  17-18-2:      2017-9-25
  17-18-3:      2018-2-26
spider:
  enable:       true
  port:         49034
  heartCycle:   40000
